/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const HatModel = React.memo(function HatModel(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/scene-transformed.glb");
  const group = useRef();

  // Animation using useFrame hook
  useFrame((state, delta) => {
    // Rotate the group
    // group.current.rotation.y += delta * 0.5; // Adjust rotation speed as needed
    // Scale the entire model
    group.current.position.set(-0.93, -0.45, 1)
    group.current.scale.set(0.45, 0.45, 0.45); // Adjust scale values as needed
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
        position={[1.481, 0.36, 0.186]}
        rotation={[-0.82, 0, 0]}
        scale={0.069}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials.PaletteMaterial002}
        position={[1.496, -0.295, -0.997]}
        rotation={[0.746, 0, 0]}
        scale={[7.58, 1.207, 1.207]}
      />
      <mesh
        geometry={nodes.Object_56.geometry}
        material={materials['Material.006']}
        position={[1.448, 1.669, -2.923]}
        rotation={[0, -0.835, 0]}
        scale={4.779}
      />
      <mesh
        geometry={nodes.Object_69.geometry}
        material={materials.PaletteMaterial003}
        position={[-5.223, 6.645, -0.581]}
        rotation={[-1.025, -0.968, -1.06]}
        scale={0.453}
      />
      <mesh
        geometry={nodes.Object_74.geometry}
        material={materials.PaletteMaterial004}
        position={[-2.843, 6.441, -1.306]}
        rotation={[1.023, -0.812, -0.689]}
        scale={0.657}
      />
      <mesh
        geometry={nodes.Object_78.geometry}
        material={materials.PaletteMaterial005}
        position={[-1.861, 4.916, -1.775]}
        rotation={[0.037, 0.38, 0.696]}
        scale={[0.321, 0.113, 0.294]}
      />
    </group>
  );
});

export default HatModel;

useGLTF.preload("/models/scene-transformed.glb");
